'use client';

import { AppHeader } from '@/components/layout/AppHeader';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import { FileText, ArrowLeft } from 'lucide-react';

export default function TermsPage() {
  const sections = [
    {
      id: 'overview',
      title: '1. Service Overview',
      content: `Ahsan AI Hub provides AI-powered tools such as:
      
• Text enhancement
• Email writing
• Blog generation
• Study assistance
• Code explanations
• Translation and more

All tools are provided free of charge and without user accounts.`
    },
    {
      id: 'accounts',
      title: '2. No User Accounts',
      content: `• No login or signup is required
• No personal profiles exist
• No stored user history`
    },
    {
      id: 'acceptable-use',
      title: '3. Acceptable Use',
      content: `You agree not to use the website for:

• Illegal activities
• Harmful, abusive, or misleading content
• Violating intellectual property laws
• Attempting to exploit or reverse-engineer the service`
    },
    {
      id: 'ai-disclaimer',
      title: '4. AI-Generated Content Disclaimer',
      content: `• Outputs are generated by AI
• Content may not always be 100% accurate
• Users should verify critical information
• We are not responsible for decisions made using AI outputs`
    },
    {
      id: 'availability',
      title: '5. Service Availability',
      content: `• We strive for high uptime
• Services may be updated, limited, or discontinued without notice
• We are not liable for temporary unavailability`
    },
    {
      id: 'liability',
      title: '6. Limitation of Liability',
      content: `Ahsan AI Hub is provided "as is". We are not liable for:

• Data loss (since no data is stored)
• Misuse of AI-generated content
• Direct or indirect damages`
    },
    {
      id: 'changes',
      title: '7. Changes to Terms',
      content: `Terms may be updated to improve clarity or compliance. Continued use of the website means acceptance of updated terms.`
    },
    {
      id: 'contact',
      title: '8. Contact',
      content: `Questions? Reach out to us at:`
    }
  ];

  return (
    <div className="flex h-full w-full flex-col bg-background selection:bg-primary/20">
      <AppHeader title="Terms of Service" />
      
      <main className="flex-1 overflow-y-auto px-4 py-12 sm:px-6 lg:px-8 flex flex-col">
        <div className="mb-8">
          <Link href="/contact">
            <Button variant="outline" className="gap-2 rounded-xl">
              <ArrowLeft className="h-4 w-4" />
              Back to Contact
            </Button>
          </Link>
        </div>
        <div className="mx-auto max-w-3xl">
          {/* Header */}
          <div className="mb-12 space-y-6">
            <div className="space-y-4">
              <div className="flex items-center gap-3">
                <FileText className="h-8 w-8 text-primary" />
                <h1 className="text-5xl font-black tracking-tight text-foreground">Terms of Service</h1>
              </div>
              <p className="text-lg text-muted-foreground">
                Legal Usage Agreement
              </p>
            </div>
          </div>

          {/* Main Content */}
          <div className="space-y-6 mb-16">
            {/* Intro */}
            <Card className="border-border/50 bg-card/40 backdrop-blur-md rounded-2xl p-8">
              <CardContent className="p-0">
                <p className="text-muted-foreground leading-relaxed">
                  By accessing or using Ahsan AI Hub, you agree to the following terms:
                </p>
              </CardContent>
            </Card>

            {/* Sections */}
            {sections.map((section) => (
              <Card key={section.id} className="border-border/50 bg-card/40 backdrop-blur-md rounded-2xl overflow-hidden">
                <CardContent className="p-8 space-y-4">
                  <h2 className="text-xl font-black text-foreground">{section.title}</h2>
                  {section.id === 'contact' ? (
                    <a 
                      href="mailto:tickets@ahsan-ai-hub.p.tawk.email"
                      className="inline-flex items-center gap-2 text-primary hover:text-primary/80 transition-colors font-bold text-lg"
                    >
                      📧 tickets@ahsan-ai-hub.p.tawk.email
                    </a>
                  ) : (
                    <div className="text-muted-foreground whitespace-pre-wrap leading-relaxed">
                      {section.content}
                    </div>
                  )}
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
